apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 448829235491.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 448829235491.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: a2bceca7
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
